/*!
* Parsley.js
* Version ${pkg.version} - built ${now.format('ddd, MMM Do YYYY, h:mm a')}
* http://parsleyjs.org
* Guillaume Potier - <guillaume@wisembly.com>
* Marc-Andre Lafortune - <petroselinum@marc-andre.ca>
* MIT Licensed
*/

// The source code below is generated by babel as
// Parsley is written in ECMAScript 6
//
